version: 2

sources:
  - name: air_quality
    description: Raw air quality data from OpenAQ API
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BIGQUERY_DATASET', 'air_quality_dataset') }}"

    freshness:
      warn_after: { count: 24, period: hour }
      error_after: { count: 48, period: hour }

    loaded_at_field: ingestion_timestamp

    tables:
      - name: measurements
        description: Raw air quality measurements
        columns:
          - name: location_id
            description: ID of the location
          - name: location
            description: Name of the location
          - name: parameter
            description: Parameter measured (PM2.5, PM10, O3, NO2, SO2, CO)
          - name: value
            description: Value of the measurement
          - name: unit
            description: Unit of measurement
          - name: city
            description: City name
          - name: country
            description: Country code
          - name: coordinates
            description: Geographical coordinates
          - name: date
            description: Date information
          - name: ingestion_timestamp
            description: Timestamp when the data was ingested

        tests:
          - unique:
              column_name: "{{ dbt_utils.generate_surrogate_key(['location_id', 'parameter', 'date.utc']) }}"
              tags: ["staging", "unique"]
          - not_null:
              column_name: value
              tags: ["staging", "not_null"]
          - not_null:
              column_name: parameter
              tags: ["staging", "not_null"]
