name: "air_quality"
version: "1.0.0"
config-version: 2

profile: "air_quality"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  air_quality:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

