default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET', 'air_quality_dataset') }}"
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: "{{ env_var('BIGQUERY_LOCATION', 'EU') }}"
      timeout_seconds: 300
      priority: interactive
      retries: 3

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET', 'air_quality_dataset') }}"
      threads: 8
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: "{{ env_var('BIGQUERY_LOCATION', 'EU') }}"
      timeout_seconds: 300
      priority: interactive
      retries: 3
