air_quality:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET', 'air_quality_dataset') }}"
      location: "{{ env_var('BIGQUERY_LOCATION', 'EU') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET', 'air_quality_dataset') }}"
      location: "{{ env_var('BIGQUERY_LOCATION', 'EU') }}"
      threads: 4
      keyfile: "/app/secrets/credentials.json"
      timeout_seconds: 300
      priority: interactive

