
api_key = "a7c05236-4348-472a-XXXX-db0a14f2d7b4" # please set me up!

# [destination.filesystem]
# # bucket_url = "bucket_url" # please set me up!
# bucket_url = "_storage" # please set me up!
# layout = "{table_name}/{YYYY}={MM}-{DD}/{load_id}.{file_id}.{ext}"
layout = "{table_name}/{YYYY}-{MM}-{DD}.{ext}"

[destination.filesystem]
bucket_url = "gs://air-quality-data-lake-de-zoomcamp-air-quality" # replace with your bucket name,

[destination.filesystem.credentials]
project_id = "de-zoomcamp-air-quality" # please set me up!
# private_key = "private_key" # please set me up!
# client_email = "client_email" # please set me up!
# DESTINATION__FILESYSTEM__CREDENTIALS__PRIVATE_KEY = XXX   # setup over env vars
# DESTINATION__FILESYSTEM__CREDENTIALS__CLIENT_EMAIL = XXX  # setup over env vars
